[2023-12-21T05:03:33.754+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 12_20_download_fx_mkt_data.first_attempt manual__2023-12-21T04:58:19.512162+00:00 [queued]>
[2023-12-21T05:03:33.789+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 12_20_download_fx_mkt_data.first_attempt manual__2023-12-21T04:58:19.512162+00:00 [queued]>
[2023-12-21T05:03:33.790+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 6
[2023-12-21T05:03:33.845+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): first_attempt> on 2023-12-21 04:58:19.512162+00:00
[2023-12-21T05:03:33.863+0000] {standard_task_runner.py:57} INFO - Started process 329 to run task
[2023-12-21T05:03:33.873+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', '12_20_download_fx_mkt_data', 'first_attempt', 'manual__2023-12-21T04:58:19.512162+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/get_fx_mkt_data.py', '--cfg-path', '/tmp/tmp923ed9ns']
[2023-12-21T05:03:33.881+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask first_attempt
[2023-12-21T05:03:34.187+0000] {task_command.py:416} INFO - Running <TaskInstance: 12_20_download_fx_mkt_data.first_attempt manual__2023-12-21T04:58:19.512162+00:00 [running]> on host af037f8bd433
[2023-12-21T05:03:34.627+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='12_20_download_fx_mkt_data' AIRFLOW_CTX_TASK_ID='first_attempt' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T04:58:19.512162+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T04:58:19.512162+00:00'
[2023-12-21T05:03:38.280+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 142, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/app/sal/etl/main.py", line 37, in main
    tickers = s3_data_service.read_excel("tickers.xlsx", sheet_name="daily")
  File "/opt/airflow/app/sal/services/boto/data_service.py", line 17, in read_excel
    return pd.read_excel(io.BytesIO(response['Body'].read()), **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 478, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1513, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 548, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 145, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2023-12-21T05:03:38.390+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=12_20_download_fx_mkt_data, task_id=first_attempt, execution_date=20231221T045819, start_date=20231221T050333, end_date=20231221T050338
[2023-12-21T05:03:38.475+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 26 for task first_attempt (Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.; 329)
[2023-12-21T05:03:38.513+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T05:03:38.686+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
