[2023-12-21T09:04:03.201+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 12_21_fx_mkt_data.first_attempt scheduled__2023-12-19T00:00:00+00:00 [queued]>
[2023-12-21T09:04:03.236+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 12_21_fx_mkt_data.first_attempt scheduled__2023-12-19T00:00:00+00:00 [queued]>
[2023-12-21T09:04:03.237+0000] {taskinstance.py:1361} INFO - Starting attempt 5 of 6
[2023-12-21T09:04:03.304+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): first_attempt> on 2023-12-19 00:00:00+00:00
[2023-12-21T09:04:03.322+0000] {standard_task_runner.py:57} INFO - Started process 870 to run task
[2023-12-21T09:04:03.332+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', '12_21_fx_mkt_data', 'first_attempt', 'scheduled__2023-12-19T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/get_fx_mkt_data.py', '--cfg-path', '/tmp/tmpy5yhcg7y']
[2023-12-21T09:04:03.340+0000] {standard_task_runner.py:85} INFO - Job 48: Subtask first_attempt
[2023-12-21T09:04:03.639+0000] {task_command.py:416} INFO - Running <TaskInstance: 12_21_fx_mkt_data.first_attempt scheduled__2023-12-19T00:00:00+00:00 [running]> on host a265892d508c
[2023-12-21T09:04:04.165+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='12_21_fx_mkt_data' AIRFLOW_CTX_TASK_ID='first_attempt' AIRFLOW_CTX_EXECUTION_DATE='2023-12-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-19T00:00:00+00:00'
[2023-12-21T09:04:04.169+0000] {oandapyV20.py:207} INFO - setting up API-client for environment practice
[2023-12-21T09:04:05.917+0000] {logging_mixin.py:154} INFO - repo_class type: <class 'abc.ABCMeta'>
[2023-12-21T09:04:05.918+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/app/sal/etl/main.py", line 50, in main
    repository_registry.add('security_symbol_repo', SecuritySymbolRepository)
  File "/opt/airflow/app/repository/registry.py", line 20, in add
    raise TypeError('repository class must be a subclass of IRepository')
TypeError: repository class must be a subclass of IRepository
[2023-12-21T09:04:05.981+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=12_21_fx_mkt_data, task_id=first_attempt, execution_date=20231219T000000, start_date=20231221T090403, end_date=20231221T090405
[2023-12-21T09:04:06.035+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 48 for task first_attempt (repository class must be a subclass of IRepository; 870)
[2023-12-21T09:04:06.101+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T09:04:06.203+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
