[2023-12-13T14:08:37.282+0000] {processor.py:157} INFO - Started process (PID=2815) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:08:37.284+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:08:37.291+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:08:37.290+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:08:37.308+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:08:37.306+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:08:37.309+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:08:37.396+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.123 seconds
[2023-12-13T14:09:08.065+0000] {processor.py:157} INFO - Started process (PID=2823) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:09:08.067+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:09:08.074+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:09:08.073+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:09:08.092+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:09:08.089+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:09:08.093+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:09:08.187+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.131 seconds
[2023-12-13T14:09:38.620+0000] {processor.py:157} INFO - Started process (PID=2831) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:09:38.623+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:09:38.632+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:09:38.631+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:09:38.650+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:09:38.647+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:09:38.651+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:09:38.744+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.135 seconds
[2023-12-13T14:10:09.421+0000] {processor.py:157} INFO - Started process (PID=2839) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:10:09.423+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:10:09.431+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:10:09.430+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:10:09.451+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:10:09.448+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:10:09.452+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:10:09.561+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.149 seconds
[2023-12-13T14:10:40.239+0000] {processor.py:157} INFO - Started process (PID=2847) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:10:40.243+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:10:40.250+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:10:40.249+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:10:40.269+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:10:40.266+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:10:40.271+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:10:40.360+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.131 seconds
[2023-12-13T14:11:10.881+0000] {processor.py:157} INFO - Started process (PID=2855) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:11:10.884+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:11:10.891+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:11:10.890+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:11:10.909+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:11:10.906+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:11:10.910+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:11:10.997+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.126 seconds
[2023-12-13T14:11:41.656+0000] {processor.py:157} INFO - Started process (PID=2863) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:11:41.658+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:11:41.664+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:11:41.663+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:11:41.682+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:11:41.680+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:11:41.683+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:11:41.775+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.128 seconds
[2023-12-13T14:12:12.404+0000] {processor.py:157} INFO - Started process (PID=2871) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:12:12.406+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:12:12.412+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:12:12.411+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:12:12.433+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:12:12.430+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:12:12.434+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:12:12.531+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.137 seconds
[2023-12-13T14:12:43.161+0000] {processor.py:157} INFO - Started process (PID=2880) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:12:43.163+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:12:43.168+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:12:43.167+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:12:43.187+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:12:43.185+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:12:43.189+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:12:43.279+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.127 seconds
[2023-12-13T14:13:13.974+0000] {processor.py:157} INFO - Started process (PID=2888) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:13:13.977+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:13:13.983+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:13:13.982+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:13:14.001+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:13:13.998+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:13:14.003+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:13:14.090+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.126 seconds
[2023-12-13T14:13:44.636+0000] {processor.py:157} INFO - Started process (PID=2896) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:13:44.638+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:13:44.644+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:13:44.643+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:13:44.664+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:13:44.661+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:13:44.666+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:13:44.753+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.127 seconds
[2023-12-13T14:14:15.266+0000] {processor.py:157} INFO - Started process (PID=2904) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:14:15.269+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:14:15.275+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:14:15.274+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:14:15.294+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:14:15.291+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:14:15.295+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:14:15.386+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.130 seconds
[2023-12-13T14:14:45.822+0000] {processor.py:157} INFO - Started process (PID=2912) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:14:45.824+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:14:45.830+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:14:45.829+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:14:45.849+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:14:45.847+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:14:45.850+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:14:45.944+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.131 seconds
[2023-12-13T14:15:16.676+0000] {processor.py:157} INFO - Started process (PID=2920) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:15:16.712+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:15:16.719+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:15:16.718+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:15:16.741+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:15:16.738+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:15:16.743+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:15:16.849+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.183 seconds
[2023-12-13T14:15:47.450+0000] {processor.py:157} INFO - Started process (PID=2928) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:15:47.454+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:15:47.460+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:15:47.459+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:15:47.479+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:15:47.476+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:15:47.480+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:15:47.573+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.132 seconds
[2023-12-13T14:16:18.016+0000] {processor.py:157} INFO - Started process (PID=2936) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:16:18.020+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:16:18.027+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:16:18.026+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:16:18.047+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:16:18.044+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:16:18.049+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:16:18.143+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.137 seconds
[2023-12-13T14:16:48.922+0000] {processor.py:157} INFO - Started process (PID=2944) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:16:48.924+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:16:48.931+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:16:48.931+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:16:48.951+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:16:48.948+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:16:48.952+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:16:49.041+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.129 seconds
[2023-12-13T14:17:19.589+0000] {processor.py:157} INFO - Started process (PID=2952) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:17:19.592+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:17:19.600+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:17:19.599+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:17:19.619+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:17:19.616+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:17:19.620+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:17:19.714+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.135 seconds
[2023-12-13T14:17:50.320+0000] {processor.py:157} INFO - Started process (PID=2960) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:17:50.322+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:17:50.329+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:17:50.328+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:17:50.346+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:17:50.343+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:17:50.347+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:17:50.438+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.127 seconds
[2023-12-13T14:18:21.014+0000] {processor.py:157} INFO - Started process (PID=2968) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:18:21.017+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:18:21.024+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:18:21.024+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:18:21.043+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:18:21.040+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:18:21.044+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:18:21.137+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.133 seconds
[2023-12-13T14:18:51.697+0000] {processor.py:157} INFO - Started process (PID=2976) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:18:51.701+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:18:51.707+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:18:51.706+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:18:51.724+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:18:51.721+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:18:51.725+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:18:51.816+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.130 seconds
[2023-12-13T14:19:22.370+0000] {processor.py:157} INFO - Started process (PID=2984) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:19:22.372+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:19:22.378+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:19:22.377+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:19:22.395+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:19:22.392+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:19:22.396+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:19:22.483+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.123 seconds
[2023-12-13T14:19:52.997+0000] {processor.py:157} INFO - Started process (PID=2992) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:19:53.000+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:19:53.006+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:19:53.006+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:19:53.025+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:19:53.023+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:19:53.027+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:19:53.118+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.131 seconds
[2023-12-13T14:20:23.805+0000] {processor.py:157} INFO - Started process (PID=3000) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:20:23.809+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:20:23.815+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:20:23.814+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:20:23.833+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:20:23.831+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:20:23.834+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:20:23.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.126 seconds
[2023-12-13T14:20:54.523+0000] {processor.py:157} INFO - Started process (PID=3008) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:20:54.525+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:20:54.531+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:20:54.530+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:20:54.550+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:20:54.547+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:20:54.552+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:20:54.639+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.126 seconds
[2023-12-13T14:21:25.155+0000] {processor.py:157} INFO - Started process (PID=3016) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:21:25.159+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:21:25.165+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:21:25.164+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:21:25.186+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:21:25.183+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:21:25.188+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:21:25.277+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.131 seconds
[2023-12-13T14:21:55.748+0000] {processor.py:157} INFO - Started process (PID=3025) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:21:55.750+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:21:55.756+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:21:55.755+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:21:55.775+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:21:55.772+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:21:55.776+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:21:55.870+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.131 seconds
[2023-12-13T14:22:26.560+0000] {processor.py:157} INFO - Started process (PID=3033) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:22:26.563+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:22:26.571+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:22:26.570+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:22:26.590+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:22:26.587+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:22:26.591+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:22:26.682+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.131 seconds
[2023-12-13T14:22:57.308+0000] {processor.py:157} INFO - Started process (PID=3041) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:22:57.311+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:22:57.318+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:22:57.317+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:22:57.336+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:22:57.334+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:22:57.337+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:22:57.427+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.128 seconds
[2023-12-13T14:23:27.943+0000] {processor.py:157} INFO - Started process (PID=3049) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:23:27.947+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:23:27.954+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:23:27.953+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:23:27.971+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:23:27.969+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:23:27.972+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:23:28.061+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.127 seconds
[2023-12-13T14:23:58.585+0000] {processor.py:157} INFO - Started process (PID=3057) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:23:58.588+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:23:58.595+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:23:58.595+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:23:58.615+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:23:58.612+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:23:58.616+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:23:58.704+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.130 seconds
[2023-12-13T14:24:29.231+0000] {processor.py:157} INFO - Started process (PID=3071) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:24:29.233+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:24:29.242+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:24:29.241+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:24:29.260+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:24:29.257+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:24:29.261+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:24:29.353+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.133 seconds
[2023-12-13T14:25:00.040+0000] {processor.py:157} INFO - Started process (PID=3080) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:25:00.042+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:25:00.049+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:25:00.049+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:25:00.068+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:25:00.065+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:25:00.069+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:25:00.161+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.131 seconds
[2023-12-13T14:25:30.620+0000] {processor.py:157} INFO - Started process (PID=3088) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:25:30.622+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:25:30.629+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:25:30.628+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:25:30.647+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:25:30.644+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:25:30.648+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:25:30.737+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.127 seconds
[2023-12-13T14:26:01.287+0000] {processor.py:157} INFO - Started process (PID=3096) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:26:01.289+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:26:01.298+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:26:01.297+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:26:01.316+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:26:01.314+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:26:01.317+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:26:01.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.143 seconds
[2023-12-13T14:26:32.114+0000] {processor.py:157} INFO - Started process (PID=3104) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:26:32.118+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:26:32.125+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:26:32.124+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:26:32.142+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:26:32.139+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:26:32.143+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:26:32.233+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.128 seconds
[2023-12-13T14:27:02.807+0000] {processor.py:157} INFO - Started process (PID=3112) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:27:02.809+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:27:02.815+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:27:02.814+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:27:02.833+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:27:02.830+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:27:02.834+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:27:02.925+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.127 seconds
[2023-12-13T14:27:33.508+0000] {processor.py:157} INFO - Started process (PID=3121) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:27:33.510+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:27:33.516+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:27:33.515+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:27:33.536+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:27:33.533+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:27:33.537+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:27:33.629+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.131 seconds
[2023-12-13T14:28:04.413+0000] {processor.py:157} INFO - Started process (PID=3129) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:28:04.418+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:28:04.424+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:28:04.423+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:28:04.442+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:28:04.439+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:28:04.444+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:28:04.535+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.131 seconds
[2023-12-13T14:28:35.121+0000] {processor.py:157} INFO - Started process (PID=3137) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:28:35.124+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:28:35.130+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:28:35.129+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:28:35.148+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:28:35.145+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:28:35.149+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:28:35.241+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.129 seconds
[2023-12-13T14:29:05.746+0000] {processor.py:157} INFO - Started process (PID=3145) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:29:05.748+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:29:05.753+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:29:05.753+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:29:05.772+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:29:05.769+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:29:05.773+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:29:05.862+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.125 seconds
[2023-12-13T14:29:36.423+0000] {processor.py:157} INFO - Started process (PID=3153) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:29:36.425+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:29:36.430+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:29:36.430+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:29:36.449+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:29:36.446+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:29:36.450+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:29:36.541+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.127 seconds
[2023-12-13T14:30:07.128+0000] {processor.py:157} INFO - Started process (PID=3161) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:30:07.130+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:30:07.137+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:30:07.136+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:30:07.156+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:30:07.153+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:30:07.157+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:30:07.254+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.137 seconds
[2023-12-13T14:30:37.867+0000] {processor.py:157} INFO - Started process (PID=3170) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:30:37.869+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:30:37.876+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:30:37.875+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:30:37.893+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:30:37.890+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:30:37.894+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:30:37.981+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.122 seconds
[2023-12-13T14:31:08.568+0000] {processor.py:157} INFO - Started process (PID=3178) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:31:08.570+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:31:08.577+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:31:08.576+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:31:08.595+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:31:08.592+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:31:08.596+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:31:08.693+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.134 seconds
[2023-12-13T14:31:39.379+0000] {processor.py:157} INFO - Started process (PID=3187) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:31:39.382+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:31:39.389+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:31:39.388+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:31:39.407+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:31:39.404+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:31:39.408+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:31:39.498+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.128 seconds
[2023-12-13T14:32:09.955+0000] {processor.py:157} INFO - Started process (PID=3194) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:32:09.957+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:32:09.963+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:32:09.962+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:32:09.980+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:32:09.978+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:32:09.982+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:32:10.069+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.125 seconds
[2023-12-13T14:32:40.761+0000] {processor.py:157} INFO - Started process (PID=3202) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:32:40.763+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:32:40.769+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:32:40.768+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:32:40.788+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:32:40.786+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:32:40.790+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:32:40.880+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.129 seconds
[2023-12-13T14:33:11.462+0000] {processor.py:157} INFO - Started process (PID=3210) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:33:11.464+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:33:11.469+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:33:11.469+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:33:11.488+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:33:11.486+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:33:11.489+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:33:11.576+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.123 seconds
[2023-12-13T14:33:42.193+0000] {processor.py:157} INFO - Started process (PID=3218) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:33:42.195+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:33:42.201+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:33:42.200+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:33:42.219+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:33:42.216+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:33:42.220+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:33:42.308+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.124 seconds
[2023-12-13T14:34:12.868+0000] {processor.py:157} INFO - Started process (PID=3226) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:34:12.870+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:34:12.875+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:34:12.875+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:34:12.894+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:34:12.892+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:34:12.895+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:34:13.028+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.169 seconds
[2023-12-13T14:34:43.660+0000] {processor.py:157} INFO - Started process (PID=3234) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:34:43.664+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:34:43.670+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:34:43.669+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:34:43.689+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:34:43.686+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:34:43.692+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:34:43.782+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.135 seconds
[2023-12-13T14:35:14.246+0000] {processor.py:157} INFO - Started process (PID=3242) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:35:14.249+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:35:14.256+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:35:14.255+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:35:14.275+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:35:14.273+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:35:14.277+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:35:14.373+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.137 seconds
[2023-12-13T14:35:45.082+0000] {processor.py:157} INFO - Started process (PID=3250) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:35:45.088+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:35:45.094+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:35:45.094+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:35:45.114+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:35:45.111+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:35:45.115+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:35:45.204+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.131 seconds
[2023-12-13T14:36:15.905+0000] {processor.py:157} INFO - Started process (PID=3258) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:36:15.906+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:36:15.912+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:36:15.911+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:36:15.931+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:36:15.928+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:36:15.932+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:36:16.022+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.126 seconds
[2023-12-13T14:36:46.680+0000] {processor.py:157} INFO - Started process (PID=3266) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:36:46.684+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:36:46.691+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:36:46.691+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:36:46.709+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:36:46.706+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:36:46.710+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:36:46.797+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.126 seconds
[2023-12-13T14:37:17.436+0000] {processor.py:157} INFO - Started process (PID=3274) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:37:17.438+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:37:17.444+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:37:17.444+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:37:17.462+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:37:17.459+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:37:17.463+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:37:17.552+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.124 seconds
[2023-12-13T14:37:48.215+0000] {processor.py:157} INFO - Started process (PID=3282) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:37:48.218+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:37:48.226+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:37:48.225+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:37:48.244+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:37:48.241+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:37:48.245+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:37:48.339+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.134 seconds
[2023-12-13T14:38:18.930+0000] {processor.py:157} INFO - Started process (PID=3290) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:38:18.932+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:38:18.939+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:38:18.938+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:38:18.956+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:38:18.954+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:38:18.958+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:38:19.046+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.125 seconds
[2023-12-13T14:38:49.590+0000] {processor.py:157} INFO - Started process (PID=3298) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:38:49.593+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:38:49.601+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:38:49.600+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:38:49.622+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:38:49.619+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:38:49.623+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:38:49.715+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.135 seconds
[2023-12-13T14:39:20.353+0000] {processor.py:157} INFO - Started process (PID=3307) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:39:20.355+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:39:20.363+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:39:20.362+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:39:20.380+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:39:20.377+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:39:20.381+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:39:20.473+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.129 seconds
[2023-12-13T14:39:50.998+0000] {processor.py:157} INFO - Started process (PID=3316) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:39:51.002+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:39:51.009+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:39:51.008+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:39:51.028+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:39:51.025+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:39:51.029+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:39:51.118+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.129 seconds
[2023-12-13T14:40:21.626+0000] {processor.py:157} INFO - Started process (PID=3324) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:40:21.628+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:40:21.636+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:40:21.635+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:40:21.654+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:40:21.652+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:40:21.655+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:40:21.745+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.128 seconds
[2023-12-13T14:40:52.456+0000] {processor.py:157} INFO - Started process (PID=3333) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:40:52.459+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:40:52.466+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:40:52.466+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:40:52.484+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:40:52.481+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:40:52.485+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:40:52.573+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.126 seconds
[2023-12-13T14:41:23.138+0000] {processor.py:157} INFO - Started process (PID=3341) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:41:23.140+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:41:23.146+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:41:23.145+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:41:23.165+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:41:23.162+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:41:23.166+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:41:23.256+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.129 seconds
[2023-12-13T14:41:53.868+0000] {processor.py:157} INFO - Started process (PID=3349) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:41:53.872+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:41:53.878+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:41:53.877+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:41:53.899+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:41:53.896+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:41:53.900+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:41:53.989+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.130 seconds
[2023-12-13T14:42:24.502+0000] {processor.py:157} INFO - Started process (PID=3357) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:42:24.504+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:42:24.510+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:42:24.509+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:42:24.529+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:42:24.526+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:42:24.530+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:42:24.623+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.131 seconds
[2023-12-13T14:42:55.289+0000] {processor.py:157} INFO - Started process (PID=3365) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:42:55.292+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:42:55.298+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:42:55.297+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:42:55.317+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:42:55.315+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:42:55.319+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:42:55.409+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.129 seconds
[2023-12-13T14:43:26.006+0000] {processor.py:157} INFO - Started process (PID=3373) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:43:26.008+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:43:26.014+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:43:26.013+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:43:26.035+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:43:26.032+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:43:26.036+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:43:26.126+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.130 seconds
[2023-12-13T14:43:56.635+0000] {processor.py:157} INFO - Started process (PID=3381) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:43:56.639+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:43:56.646+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:43:56.645+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:43:56.664+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:43:56.662+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:43:56.666+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:43:56.756+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.130 seconds
[2023-12-13T14:44:27.339+0000] {processor.py:157} INFO - Started process (PID=3390) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:44:27.341+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:44:27.347+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:44:27.346+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:44:27.368+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:44:27.365+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:44:27.370+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:44:27.458+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.129 seconds
[2023-12-13T14:44:57.977+0000] {processor.py:157} INFO - Started process (PID=3398) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:44:57.979+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:44:57.986+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:44:57.985+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:44:58.004+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:44:58.001+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:44:58.005+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:44:58.097+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.129 seconds
[2023-12-13T14:45:28.667+0000] {processor.py:157} INFO - Started process (PID=3406) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:45:28.669+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:45:28.677+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:45:28.676+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:45:28.696+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:45:28.693+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:45:28.697+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:45:28.790+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.132 seconds
[2023-12-13T14:45:59.368+0000] {processor.py:157} INFO - Started process (PID=3414) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:45:59.372+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:45:59.379+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:45:59.378+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:45:59.398+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:45:59.395+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:45:59.400+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:45:59.489+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.130 seconds
[2023-12-13T14:46:30.024+0000] {processor.py:157} INFO - Started process (PID=3422) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:46:30.026+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:46:30.033+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:46:30.032+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:46:30.051+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:46:30.048+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:46:30.052+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:46:30.147+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.132 seconds
[2023-12-13T14:47:00.824+0000] {processor.py:157} INFO - Started process (PID=3430) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:47:00.827+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:47:00.833+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:47:00.832+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:47:00.851+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:47:00.848+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:47:00.852+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:47:00.946+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.132 seconds
[2023-12-13T14:47:31.507+0000] {processor.py:157} INFO - Started process (PID=3438) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:47:31.510+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:47:31.516+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:47:31.515+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:47:31.535+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:47:31.532+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:47:31.536+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:47:31.627+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.130 seconds
[2023-12-13T14:48:02.064+0000] {processor.py:157} INFO - Started process (PID=3447) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:48:02.068+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:48:02.074+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:48:02.073+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:48:02.094+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:48:02.091+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:48:02.095+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:48:02.188+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.134 seconds
[2023-12-13T14:48:32.941+0000] {processor.py:157} INFO - Started process (PID=3455) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:48:32.943+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:48:32.949+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:48:32.948+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:48:32.968+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:48:32.965+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:48:32.970+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:48:33.060+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.128 seconds
[2023-12-13T14:49:03.724+0000] {processor.py:157} INFO - Started process (PID=3463) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:49:03.728+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:49:03.733+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:49:03.732+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:49:03.752+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:49:03.749+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:49:03.753+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:49:03.845+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.130 seconds
[2023-12-13T14:49:34.343+0000] {processor.py:157} INFO - Started process (PID=3472) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:49:34.345+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:49:34.351+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:49:34.350+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:49:34.369+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:49:34.367+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:49:34.370+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:49:34.458+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.123 seconds
[2023-12-13T14:50:05.041+0000] {processor.py:157} INFO - Started process (PID=3480) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:50:05.044+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:50:05.049+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:50:05.049+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:50:05.068+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:50:05.065+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:50:05.069+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:50:05.157+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.125 seconds
[2023-12-13T14:50:35.810+0000] {processor.py:157} INFO - Started process (PID=3488) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:50:35.811+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:50:35.817+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:50:35.816+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:50:35.837+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:50:35.834+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:50:35.838+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:50:35.928+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.127 seconds
[2023-12-13T14:51:06.622+0000] {processor.py:157} INFO - Started process (PID=3496) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:51:06.626+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:51:06.631+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:51:06.630+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:51:06.650+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:51:06.648+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:51:06.652+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:51:06.738+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.125 seconds
[2023-12-13T14:51:37.288+0000] {processor.py:157} INFO - Started process (PID=3504) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:51:37.290+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:51:37.295+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:51:37.295+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:51:37.314+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:51:37.312+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:51:37.315+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:51:37.409+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.130 seconds
[2023-12-13T14:52:08.161+0000] {processor.py:157} INFO - Started process (PID=3512) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:52:08.163+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:52:08.171+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:52:08.170+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:52:08.191+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:52:08.188+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:52:08.192+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:52:08.282+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.130 seconds
[2023-12-13T14:52:38.826+0000] {processor.py:157} INFO - Started process (PID=3526) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:52:38.828+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:52:38.836+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:52:38.835+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:52:38.853+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:52:38.851+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:52:38.854+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:52:38.959+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.144 seconds
[2023-12-13T14:53:09.516+0000] {processor.py:157} INFO - Started process (PID=3536) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:53:09.520+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:53:09.528+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:53:09.527+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:53:09.547+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:53:09.544+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:53:09.548+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:53:09.639+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.132 seconds
[2023-12-13T14:53:40.333+0000] {processor.py:157} INFO - Started process (PID=3544) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:53:40.335+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:53:40.340+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:53:40.339+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:53:40.358+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:53:40.355+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:53:40.359+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:53:40.447+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.124 seconds
[2023-12-13T14:54:10.982+0000] {processor.py:157} INFO - Started process (PID=3552) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:54:10.987+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:54:10.994+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:54:10.993+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:54:11.014+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:54:11.011+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:54:11.015+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:54:11.102+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.129 seconds
[2023-12-13T14:54:41.633+0000] {processor.py:157} INFO - Started process (PID=3560) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:54:41.635+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:54:41.641+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:54:41.640+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:54:41.659+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:54:41.657+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:54:41.661+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:54:41.749+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.125 seconds
[2023-12-13T14:55:12.396+0000] {processor.py:157} INFO - Started process (PID=3567) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:55:12.400+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:55:12.406+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:55:12.405+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:55:12.429+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:55:12.426+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:55:12.430+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:55:12.518+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.131 seconds
[2023-12-13T14:55:43.188+0000] {processor.py:157} INFO - Started process (PID=3575) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:55:43.190+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:55:43.197+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:55:43.196+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:55:43.217+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:55:43.214+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:55:43.218+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:55:43.308+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.130 seconds
[2023-12-13T14:56:13.875+0000] {processor.py:157} INFO - Started process (PID=3583) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:56:13.878+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:56:13.884+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:56:13.883+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:56:13.903+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:56:13.900+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:56:13.904+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:56:13.994+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.128 seconds
[2023-12-13T14:56:44.650+0000] {processor.py:157} INFO - Started process (PID=3591) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:56:44.652+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:56:44.658+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:56:44.657+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:56:44.676+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:56:44.674+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:56:44.677+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:56:44.770+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.129 seconds
[2023-12-13T14:57:15.319+0000] {processor.py:157} INFO - Started process (PID=3599) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:57:15.323+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:57:15.329+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:57:15.328+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:57:15.348+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:57:15.345+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:57:15.349+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:57:15.441+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.131 seconds
[2023-12-13T14:57:46.131+0000] {processor.py:157} INFO - Started process (PID=3607) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:57:46.135+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:57:46.141+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:57:46.140+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:57:46.160+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:57:46.157+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:57:46.161+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:57:46.248+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.126 seconds
[2023-12-13T14:58:16.936+0000] {processor.py:157} INFO - Started process (PID=3615) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:58:16.940+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:58:16.947+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:58:16.946+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:58:16.965+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:58:16.962+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:58:16.966+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:58:17.062+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.135 seconds
[2023-12-13T14:58:47.736+0000] {processor.py:157} INFO - Started process (PID=3623) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:58:47.739+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:58:47.746+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:58:47.745+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:58:47.764+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:58:47.761+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:58:47.766+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:58:47.857+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.130 seconds
[2023-12-13T14:59:18.420+0000] {processor.py:157} INFO - Started process (PID=3630) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:59:18.422+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:59:18.430+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:59:18.429+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:59:18.451+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:59:18.448+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:59:18.452+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:59:18.540+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.131 seconds
[2023-12-13T14:59:49.010+0000] {processor.py:157} INFO - Started process (PID=3639) to work on /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:59:49.012+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/__pycache__/get_fx_mkt_data.py for tasks to queue
[2023-12-13T14:59:49.019+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:59:49.019+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:59:49.037+0000] {logging_mixin.py:154} INFO - [2023-12-13T14:59:49.034+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/get_fx_mkt_data.py", line 6, in <module>
    from services.oanda import fx_daily_update
ModuleNotFoundError: No module named 'services'
[2023-12-13T14:59:49.038+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/get_fx_mkt_data.py
[2023-12-13T14:59:49.132+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/__pycache__/get_fx_mkt_data.py took 0.132 seconds
