[2023-12-21T09:47:07.164+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 12_21_fx_mkt_data.first_attempt manual__2023-12-21T09:47:02.437385+00:00 [queued]>
[2023-12-21T09:47:07.198+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 12_21_fx_mkt_data.first_attempt manual__2023-12-21T09:47:02.437385+00:00 [queued]>
[2023-12-21T09:47:07.199+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-21T09:47:07.262+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): first_attempt> on 2023-12-21 09:47:02.437385+00:00
[2023-12-21T09:47:07.279+0000] {standard_task_runner.py:57} INFO - Started process 1471 to run task
[2023-12-21T09:47:07.291+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', '12_21_fx_mkt_data', 'first_attempt', 'manual__2023-12-21T09:47:02.437385+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/get_fx_mkt_data.py', '--cfg-path', '/tmp/tmp_5v9q6sx']
[2023-12-21T09:47:07.299+0000] {standard_task_runner.py:85} INFO - Job 68: Subtask first_attempt
[2023-12-21T09:47:07.547+0000] {task_command.py:416} INFO - Running <TaskInstance: 12_21_fx_mkt_data.first_attempt manual__2023-12-21T09:47:02.437385+00:00 [running]> on host a265892d508c
[2023-12-21T09:47:07.937+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='12_21_fx_mkt_data' AIRFLOW_CTX_TASK_ID='first_attempt' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T09:47:02.437385+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T09:47:02.437385+00:00'
[2023-12-21T09:47:07.941+0000] {oandapyV20.py:207} INFO - setting up API-client for environment practice
[2023-12-21T09:47:09.082+0000] {oandapyV20.py:261} INFO - performing request https://api-fxpractice.oanda.com/v3/instruments/EUR_USD/candles
[2023-12-21T09:47:09.570+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/app/sal/etl/main.py", line 61, in main
    data = fx_data_service.fetch_historical_data(instrument=instrument, start_date=_from, granularity=granularity)
  File "/opt/airflow/app/sal/services/oanda/data_service.py", line 57, in fetch_historical_data
    df = pd.DataFrame(full_data, columns=['time', 'volume', 'open', 'high', 'low', 'close'])
NameError: name 'pd' is not defined
[2023-12-21T09:47:09.630+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=12_21_fx_mkt_data, task_id=first_attempt, execution_date=20231221T094702, start_date=20231221T094707, end_date=20231221T094709
[2023-12-21T09:47:09.675+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 68 for task first_attempt (name 'pd' is not defined; 1471)
[2023-12-21T09:47:09.736+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T09:47:09.827+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
