[2023-12-20T16:21:25.335+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 12_20_download_fx_mkt_data.first_attempt manual__2023-12-20T16:19:10.204363+00:00 [queued]>
[2023-12-20T16:21:25.368+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 12_20_download_fx_mkt_data.first_attempt manual__2023-12-20T16:19:10.204363+00:00 [queued]>
[2023-12-20T16:21:25.369+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 7
[2023-12-20T16:21:25.420+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): first_attempt> on 2023-12-20 16:19:10.204363+00:00
[2023-12-20T16:21:25.436+0000] {standard_task_runner.py:57} INFO - Started process 6690 to run task
[2023-12-20T16:21:25.445+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', '12_20_download_fx_mkt_data', 'first_attempt', 'manual__2023-12-20T16:19:10.204363+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/get_fx_mkt_data.py', '--cfg-path', '/tmp/tmplfvfcwlb']
[2023-12-20T16:21:25.451+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask first_attempt
[2023-12-20T16:21:25.689+0000] {task_command.py:416} INFO - Running <TaskInstance: 12_20_download_fx_mkt_data.first_attempt manual__2023-12-20T16:19:10.204363+00:00 [running]> on host 39ff41744a35
[2023-12-20T16:21:26.078+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='12_20_download_fx_mkt_data' AIRFLOW_CTX_TASK_ID='first_attempt' AIRFLOW_CTX_EXECUTION_DATE='2023-12-20T16:19:10.204363+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-20T16:19:10.204363+00:00'
[2023-12-20T16:21:35.708+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-12-20T16:21:35.716+0000] {process_utils.py:131} INFO - Sending 15 to group 6690. PIDs of all processes in the group: [6690]
[2023-12-20T16:21:35.717+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 6690
[2023-12-20T16:21:35.717+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-12-20T16:21:35.850+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=6690, status='terminated', exitcode=0, started='16:21:24') (6690) terminated with exit code 0
